/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

/**
 *
 * @author Jorge Luis
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public frmMenuPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuTriangulo = new javax.swing.JMenuItem();
        mnuRectangulo = new javax.swing.JMenuItem();
        mnuCircunferencia = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuInformacion = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Figuras Geometricas");

        mnuTriangulo.setText("Triangulo");
        mnuTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTrianguloActionPerformed(evt);
            }
        });
        jMenu1.add(mnuTriangulo);

        mnuRectangulo.setText("Rectangulo");
        mnuRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRectanguloActionPerformed(evt);
            }
        });
        jMenu1.add(mnuRectangulo);

        mnuCircunferencia.setText("Circunferencia");
        mnuCircunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCircunferenciaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCircunferencia);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informacion Personal");

        mnuInformacion.setText("Informacion");
        mnuInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInformacionActionPerformed(evt);
            }
        });
        jMenu2.add(mnuInformacion);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTrianguloActionPerformed
        // TODO add your handling code here:
        frmTriangulo objT=new frmTriangulo();
        Contenedor.add(objT);
        objT.setVisible(true);
    }//GEN-LAST:event_mnuTrianguloActionPerformed

    private void mnuRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRectanguloActionPerformed
        // TODO add your handling code here:
        frmRectangulo objR=new frmRectangulo();
        Contenedor.add(objR);
        objR.setLocation(500, 0);
        objR.setVisible(true);
    }//GEN-LAST:event_mnuRectanguloActionPerformed

    private void mnuCircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCircunferenciaActionPerformed
        // TODO add your handling code here:
        frmCircunferencia objC=new frmCircunferencia();
        Contenedor.add(objC);
        objC.setLocation(940, 0);
        objC.setVisible(true);
    }//GEN-LAST:event_mnuCircunferenciaActionPerformed

    private void mnuInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInformacionActionPerformed
        // TODO add your handling code here:
        frmInformacionPersonal objI= new frmInformacionPersonal();
        Contenedor.add(objI);
        objI.setVisible(true);
    }//GEN-LAST:event_mnuInformacionActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCircunferencia;
    private javax.swing.JMenuItem mnuInformacion;
    private javax.swing.JMenuItem mnuRectangulo;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuTriangulo;
    // End of variables declaration//GEN-END:variables
}
